version: '3'
services:
  app:
    build: .
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql:8.0.32
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokecard
    ports:
      - "3306:3306" 
volumes:
  db_data:
